### ISSUE TITLE
Soccer issue

### ISSUE THREAD

**Issue by sadalavoaoj** [bk2dcradle/BPL-Score-Updates#1]
Hi there,

Someone have problems with soccer results? I can see everything except  soccer updates.
if someone now any fix, i would apreciate to know HOW to receive soccer updates too.

**Comment by bk2dcradle** [comment]
Can you be a little more specific? What exactly are you able to see? Note that you need to install Beautiful Soup in order to run the script successfully. [Instructions](http://www.crummy.com/software/BeautifulSoup/bs4/doc/).

**Comment by sadalavoaoj** [comment]
I didnt installed nothing, except the score-updates applet in cinnamon applets. Maybe im in wrong theme? as i see this is not for linux am i on the wrong window?

Thanks,

**Comment by bk2dcradle** [comment]
The script is OS X only.

**Comment by sadalavoaoj** [comment]
Ok, Thanks anyway, and sorry for the question.
